Page({
  data: {
          msg:"hello",
          num:10000,
          isfalse:true,
          person:
          {
            age:74,
            name:"人"
          },
          ischecked:false,
          list:[
            {
              id:0,
              name:"hhw0"
            },
            {
              id:1,
              name:"hhw1"
            },
            {
              id:2,
              name:"hhw2"
            }
          ]
  }
})